[versions]
junit = "4.13.2"
jetbrainsKotlinJvm = "1.9.23"
kotlinpoet = "1.16.0"
ksp = "1.9.23-1.0.19"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
compiletesting = { group = "com.github.tschuchortdev", name = "kotlin-compile-testing-ksp", version = "1.5.0" }

[plugins]
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.28.0" }
